### PR TITLE
Cleanup and update of outdated images

### PR DESCRIPTION
**Pull request by almusil**
Do some smaller cleanup to the setup and the container packages.

### CODE REVIEW

**Comment by flavio-fernandes** [comment]
/lgtm
Thanks for the cleanup.
@dceara @numansiddique could you also take a look to make sure these do not disrupt anything you depend on (ovn-heater)?

**Comment by numansiddique** [comment]
Thanks for the PR.  Looks good to me.

**Comment by numansiddique** [comment]
@dceara  For ovn-heater testing,  I had noticed few issues using fedora 35 container  with rhel8.
But I guess we can override the image to fedora 31 if required.

I'll go ahead and merge it.

**Comment by almusil** [comment]
> @dceara For ovn-heater testing, I had noticed few issues using fedora 35 container with rhel8. But I guess we can override the image to fedora 31 if required.
> 
> I'll go ahead and merge it.

What are those issues? Maybe it can be solved by tweaking the image rather than using version that is EOL for some time.

**Comment by dceara** [comment]
> > @dceara For ovn-heater testing, I had noticed few issues using fedora 35 container with rhel8. But I guess we can override the image to fedora 31 if required.
> > I'll go ahead and merge it.
> 
> @numansiddique What are those issues? Maybe it can be solved by tweaking the image rather than using version that is EOL for some time.

@numansiddique ovn-heater will use whatever is running on the host unless the image is explicitly overridden.  I don't think I ever tried a combination like fedora 35 in the container and rhel8 on the host.  In any case, our downstream test infra overrides the image and use ubi8:5.

It just happens that our downstream automation already picked up this PR last night and things still work fine so it's all good.

Thanks for the cleanup @almusil!

**Comment by dceara** [comment]
> It just happens that our downstream automation already picked up this PR last night and things still work fine so it's all good.

I take this back, sorry.  I just noticed that the build command actually fails mid way with this PR applied:
```
STEP 8/12: RUN /install_pkg.sh $OS_IMAGE
+ dnf -y install systemd
Updating Subscription Management repositories.
Unable to read consumer identity
Subscription Manager is operating in container mode.
Red Hat Enterprise Linux 8 for x86_64 - AppStre  42 MB/s |  39 MB     00:00    
Red Hat Enterprise Linux 8 for x86_64 - BaseOS   40 MB/s |  45 MB     00:01    
Red Hat Universal Base Image 8 (RPMs) - BaseOS  4.8 MB/s | 798 kB     00:00    
Red Hat Universal Base Image 8 (RPMs) - AppStre  15 MB/s | 2.6 MB     00:00    
Red Hat Universal Base Image 8 (RPMs) - CodeRea 161 kB/s |  17 kB     00:00    
Package systemd-239-51.el8_5.5.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
+ systemctl mask auditd.service console-getty.service dev-hugepages.mount dnf-makecache.service getty.target lvm2-lvmetad.service sys-fs-fuse-connections.mount systemd-logind.service systemd-remount-fs.service systemd-udev-hwdb-update.service systemd-udevd.service systemd-vconsole-setup.service
Created symlink /etc/systemd/system/auditd.service â†’ /dev/null.
Created symlink /etc/systemd/system/dnf-makecache.service â†’ /dev/null.
Created symlink /etc/systemd/system/lvm2-lvmetad.service â†’ /dev/null.
Created symlink /etc/systemd/system/systemd-udev-hwdb-update.service â†’ /dev/null.
Created symlink /etc/systemd/system/systemd-udevd.service â†’ /dev/null.
Created symlink /etc/systemd/system/systemd-vconsole-setup.service â†’ /dev/null.
+ dnf -y install autoconf automake conntrack-tools dhcp-client dnf-utils file fping gcc gettext-devel git glibc-langpack-en hostname iproute iproute.x86_64 iptables libcap-devel libreswan libtool libxslt lksctp-tools-devel make meson net-tools.x86_64 ninja-build nmap openssh-clients openssh-server openssl openssl-devel perf procps-ng python3 python3-pip resource-agents tcpdump uuid.x86_64 which
Updating Subscription Management repositories.
Unable to read consumer identity
Subscription Manager is operating in container mode.
Last metadata expiration check: 0:00:06 ago on Fri Apr  8 04:01:42 2022.
No match for argument: fping
No match for argument: meson
No match for argument: ninja-build
No match for argument: resource-agents
Package which-2.21-16.el8.x86_64 is already installed.
Error: Unable to find a match: fping meson ninja-build resource-agents
Error: error building at STEP "RUN /install_pkg.sh $OS_IMAGE": error while running runtime: exit status 1
```
I'll have a look and see why.  This actually uncovered a problem in ovn-heater, not failing if building the images fails.

**Pull request merged**
