### PR TITLE
Push ovn-fake-multinode base image to ghcr.io

### PR DESCRIPTION
**Pull request by numansiddique**
This would be helpful for ovn project to build ovn-fake-multinode using this base image in CI.

Signed-off-by: Numan Siddique <numans@ovn.org>

### CODE REVIEW

**Comment by numansiddique** [comment]
A trial run of this workflow can be found here - https://github.com/ovn-org/ovn-fake-multinode/actions/runs/3635493765/jobs/6134640686

Created a temporary branch - "testing" to test this out.

**Comment by flavio-fernandes** [comment]
very cool! 
/lgtm

**Comment by numansiddique** [comment]
I'll update the PR to also push the ovn-fake-multinode image.

**Comment by dceara** [comment]
@numansiddique is this one still applicable?

Thanks,
Dumitru

**Comment by numansiddique** [comment]
@dceara I think this is probably good to have.  But no urgent requirement

**Pull request closed without merging**
