### PR TITLE
Fix for ovn-ic

### PR DESCRIPTION
**Pull request by LorenzoBianconi**

### CODE REVIEW

**Comment by numansiddique** [comment]
@LorenzoBianconi  Signed-off-by tag please

**Comment by LorenzoBianconi** [comment]
> @LorenzoBianconi Signed-off-by tag please

@numansiddique done

**Comment by numansiddique** [comment]
@LorenzoBianconi Cn you plz rebase and trigger another CI run ?

**Comment by igsilya** [comment]
@numansiddique @LorenzoBianconi This change seems to have broken ovn-heater for the case with OVN-IC with standalone databases.  In this case the `CLUSTER_IC_ID` is defined as `ovn-central-az0` <-- see that there is no `-1` suffix and so it fails to find the container:

```
TASK [Start central containers] ************************************************
failed: [server03] (item=0) => {
  "ansible_loop_var": "item",
  "changed": true,
  "cmd": "./ovn_cluster.sh start\n",
  "delta": "0:00:03.577927",
  "end": "2024-11-30 02:01:20.587213",
  "item": 0,
  "msg": "non-zero return code",
  "rc": 125,
  "start": "2024-11-30 02:01:17.009286",
  "stderr": "Error: no container with name or ID \"ovn-central-az0\" found: no such container",
  "stderr_lines": [
    "Error: no container with name or ID \"ovn-central-az0\" found: no such container"
  ],
  "stdout": "Starting OVN cluster\nWaiting for containers to be up..\nAdding ovs-ports\n/etc/ovn/ovnnb_db.db does not exist ... (warning).\nCreating empty database /etc/ovn/ovnnb_db.db [  OK  ]\r\nStarting ovsdb-nb [  OK  ]\r\n/etc/ovn/ovnsb_db.db does not exist ... (warning).\nCreating empty database /etc/ovn/ovnsb_db.db [  OK  ]\r\nStarting ovsdb-sb [  OK  ]\r\nStarting ovn-northd [  OK  ]",
  "stdout_lines": [
    "Starting OVN cluster",
    "Waiting for containers to be up..",
    "Adding ovs-ports",
    "/etc/ovn/ovnnb_db.db does not exist ... (warning).",
    "Creating empty database /etc/ovn/ovnnb_db.db [  OK  ]",
    "Starting ovsdb-nb [  OK  ]",
    "/etc/ovn/ovnsb_db.db does not exist ... (warning).",
    "Creating empty database /etc/ovn/ovnsb_db.db [  OK  ]",
    "Starting ovsdb-sb [  OK  ]",
    "Starting ovn-northd [  OK  ]"
  ]
}
```

The suffix must be added only for the clustered case.  At least, the users do not expect to have to add the suffix.
Could you, please, take a look?

**Pull request merged**
