### PR TITLE
Add basic versioning support.

### PR DESCRIPTION
**Pull request by dceara**
Signed-off-by: Dumitru Ceara <dceara@redhat.com>

### CODE REVIEW

**Comment by putnopvut** [comment]
Seems fine. Any idea what would cause us to change the version number? What would qualify for a 1.0?

**Comment by dceara** [comment]
> Seems fine. Any idea what would cause us to change the version number? What would qualify for a 1.0?

@putnopvut The main reason behind a version would be to make it easier to tag  "stable" versions of the code so that other users of the project can choose a human readable tag instead of a commit SHA. Always pointing to the master version of `ovn-fake-multinode` in other projects doesn't seem like a good idea on the long run as things sometimes break on master branches.

Regarding when we'd change the version number, I guess it depends whether we decide to go for periodic releases or not.

Regarding how we'd change the version number, one option would be to have two types of releases:
- bug-fix release: bump the version to `<major>.<minor>+1`
- major release (i.e., new features): bump the version to `<major>+1.0`

@numansiddique @flavio-fernandes, any thoughts?

Thanks,
Dumitru

**Comment by flavio-fernandes** [comment]
> > Seems fine. Any idea what would cause us to change the version number? What would qualify for a 1.0?
> 
> @putnopvut The main reason behind a version would be to make it easier to tag "stable" versions of the code so that other users of the project can choose a human readable tag instead of a commit SHA. Always pointing to the master version of `ovn-fake-multinode` in other projects doesn't seem like a good idea on the long run as things sometimes break on master branches.
> 
> Regarding when we'd change the version number, I guess it depends whether we decide to go for periodic releases or not.
> 
> Regarding how we'd change the version number, one option would be to have two types of releases:
> 
>     * bug-fix release: bump the version to `<major>.<minor>+1`
> 
>     * major release (i.e., new features): bump the version to `<major>+1.0`
> 
> 
> @numansiddique @flavio-fernandes, any thoughts?
> 
> Thanks,
> Dumitru

I am 100% in agreement on what you said, @dceara .

**Comment by dceara** [comment]
@putnopvut @flavio-fernandes @numansiddique Thanks for the comments and reviews! Merging this now.

**Pull request merged**
