### PR TITLE
Remove sudo access in etcd and ovsdb-etcd install

### PR DESCRIPTION
**Pull request by msherif1234**
Signed-off-by: Mohamed S. Mahmoud <mmahmoud@redhat.com>
no need for sudo we already running as root

### CODE REVIEW

**Review by flavio-fernandes — APPROVED** [review]

**Review by flavio-fernandes — CHANGES_REQUESTED** [review]
heh, since you are cleaning this up... could you also remove:

https://github.com/ovn-org/ovn-fake-multinode/blob/16f7f7a1519a3e3c5ac251c991ed954b19fdf275/ovn_cluster.sh#L63

and make 

https://github.com/ovn-org/ovn-fake-multinode/blob/16f7f7a1519a3e3c5ac251c991ed954b19fdf275/ovn_cluster.sh#L514

use the `USE_OVSDB_ETCD` variable? This seems redundant/confusing right now.

**Comment by msherif1234** [comment]
> heh, since you are cleaning this up... could you also remove:
> 
> https://github.com/ovn-org/ovn-fake-multinode/blob/16f7f7a1519a3e3c5ac251c991ed954b19fdf275/ovn_cluster.sh#L63
> 
> and make
> 
> https://github.com/ovn-org/ovn-fake-multinode/blob/16f7f7a1519a3e3c5ac251c991ed954b19fdf275/ovn_cluster.sh#L514
> 
> use the `USE_OVSDB_ETCD` variable? This seems redundant/confusing right now.
I thought the same but I was considering cases where we have etcd installed but I need to run w/o it to compare if needed , not sure might be not needed

**Comment by msherif1234** [comment]
> > heh, since you are cleaning this up... could you also remove:
> > https://github.com/ovn-org/ovn-fake-multinode/blob/16f7f7a1519a3e3c5ac251c991ed954b19fdf275/ovn_cluster.sh#L63
> > 
> > and make
> > https://github.com/ovn-org/ovn-fake-multinode/blob/16f7f7a1519a3e3c5ac251c991ed954b19fdf275/ovn_cluster.sh#L514
> > 
> > use the `USE_OVSDB_ETCD` variable? This seems redundant/confusing right now.
> > I thought the same but I was considering cases where we have etcd installed but I need to run w/o it to compare if needed , not sure might be not needed

actually they serve different purposes one is used during the build while the other is used runtime

**Comment by flavio-fernandes** [comment]
> > > heh, since you are cleaning this up... could you also remove:
> > > https://github.com/ovn-org/ovn-fake-multinode/blob/16f7f7a1519a3e3c5ac251c991ed954b19fdf275/ovn_cluster.sh#L63
> > > 
> > > and make
> > > https://github.com/ovn-org/ovn-fake-multinode/blob/16f7f7a1519a3e3c5ac251c991ed954b19fdf275/ovn_cluster.sh#L514
> > > 
> > > use the `USE_OVSDB_ETCD` variable? This seems redundant/confusing right now.
> > > I thought the same but I was considering cases where we have etcd installed but I need to run w/o it to compare if needed , not sure might be not needed
> 
> actually they serve different purposes one is used during the build while the other is used runtime

hmm... okay. But we cannot have one w/out the other, no? I don't think it makes sense to enable etcd if we are not going to use it. If you really intended to have 2 different knobs, then I accept it; but if it was a mistake I'd much rather have these 2 things (build and runtime) use the same variable. What do you think?

**Review by flavio-fernandes — APPROVED** [review]
lgtm. Thanks for the clarification on USE_OVSDB_ETCD!

**Pull request merged**
