### PR TITLE
Rocky8

### PR DESCRIPTION
**Pull request by flavio-fernandes**
- Vagrant: use rocky8 as base image
- use ovs submodule

### CODE REVIEW

**Review by numansiddique — APPROVED** [review]

**Comment by numansiddique** [comment]
lgtm

**Review by almusil — APPROVED** [review]

**Review by dceara — CHANGES_REQUESTED** [review]
@flavio-fernandes I'm afraid we still need OVS_SRC_PATH.

There are two different types of compatibility:
- compile-time: OVN should be compiled against the supported version, which is what your PR does.
- run-time: the user should be able to run against any supported OVS version which may (and in real scenarios usually is) different than what OVN points to in the submodule.

Basically this means that we need to build OVS twice:
- first from the submodule (later compile OVN against it)
- second from OVS_SRC_PATH, and actually install this version.

Otherwise OVS binaries (and ovsdb-server) will be built from the sources in the submodule version which is not ideal.

**Comment by dceara** [comment]
@flavio-fernandes What do you think of the following incremental?  I didn't test the vagrant part but I did test building OVN main with OVS master (which currently breaks API compatibility for `inet_parse_active()`).

~~~
diff --git a/README.md b/README.md
index f5189ed..d630f56 100644
--- a/README.md
+++ b/README.md
@@ -18,7 +18,7 @@ Step 1: Build the container images
 
 By default, Docker is used (we can switch to Podman later):
 ```
-sudo OVN_SRC_PATH=<path_t_ovn_src_folder> ./ovn_cluster.sh build
+sudo OVN_SRC_PATH=<path_t_ovn_src_folder> OVS_SRC_PATH=<path_to_ovs_src_folder> ./ovn_cluster.sh build
 ```
 
 This will create 2 docker images
diff --git a/Vagrantfile b/Vagrantfile
index 43a06a0..ff34985 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -13,7 +13,7 @@ SCRIPT
 
 $build_images = <<SCRIPT
 cd /vagrant && \
-OVN_SRC_PATH=./ovn time ./ovn_cluster.sh build
+OVN_SRC_PATH=./ovn OVS_SRC_PATH=./ovs time ./ovn_cluster.sh build
 SCRIPT
 
 $start_ovn_cluster = <<SCRIPT
@@ -42,6 +42,9 @@ Vagrant.configure(2) do |config|
       config.vm.synced_folder ".", "/vagrant", type: "rsync"
     end
 
+    if ENV['OVS_DIR']
+        config.vm.synced_folder ENV['OVS_DIR'], '/vagrant/ovs', type: 'rsync'
+    end
     if ENV['OVN_DIR']
         config.vm.synced_folder ENV['OVN_DIR'], '/vagrant/ovn', type: 'rsync'
     end
diff --git a/fedora/ovn/Dockerfile b/fedora/ovn/Dockerfile
index 528877f..03508e7 100644
--- a/fedora/ovn/Dockerfile
+++ b/fedora/ovn/Dockerfile
@@ -1,12 +1,14 @@
 FROM ovn/cinc
 MAINTAINER "Numan Siddique" <numans@ovn.org>
 
+ARG OVS_SRC_PATH
 ARG OVN_SRC_PATH
 ARG USE_OVN_RPMS
 ARG EXTRA_OPTIMIZE
 ARG INSTALL_UTILS_FROM_SOURCES
 ARG USE_OVSDB_ETCD
 
+COPY $OVS_SRC_PATH /ovs
 COPY $OVN_SRC_PATH /ovn
 
 COPY *.rpm /
diff --git a/install_ovn.sh b/install_ovn.sh
index 828bc38..5362518 100755
--- a/install_ovn.sh
+++ b/install_ovn.sh
@@ -30,8 +30,17 @@ if [ "$use_ovn_rpm" = "yes" ]; then
 else
     mkdir -p /root/ovsdb-etcd/schemas
 
+    # Build OVS binaries and install them.
+    cd /ovs
+    ./boot.sh
+    ./configure --localstatedir="/var" --sysconfdir="/etc" --prefix="/usr" \
+    --enable-ssl --disable-libcapng --enable-Werror CFLAGS="${cflags}"
+    make -j$(($(nproc) + 1)) V=0
+    make install
+    cp ./ovsdb/_server.ovsschema /root/ovsdb-etcd/schemas/
+
+    # Build OVS libraries from submodule, needed by OVN.
     cd /ovn
-    # get ovs source always, as its needed as dependency
     rm -rf ./ovs
     git submodule update --init
 
@@ -41,8 +50,6 @@ else
     ./configure --localstatedir="/var" --sysconfdir="/etc" --prefix="/usr" \
     --enable-ssl --disable-libcapng --enable-Werror CFLAGS="${cflags}"
     make -j$(($(nproc) + 1)) V=0
-    make install
-    cp ./ovsdb/_server.ovsschema /root/ovsdb-etcd/schemas/
 
     cd /ovn
     # build and install
@@ -69,4 +76,4 @@ popd
 dnf autoremove -y
 
 
-rm -rf /ovn
+rm -rf /ovs /ovn
diff --git a/ovn_cluster.sh b/ovn_cluster.sh
index 2dc43cc..09fce31 100755
--- a/ovn_cluster.sh
+++ b/ovn_cluster.sh
@@ -36,6 +36,7 @@ OVN_BR_CLEANUP="${OVN_BR_CLEANUP:-yes}"
 OVS_DOCKER="./ovs-docker"
 
 OVN_SRC_PATH="${OVN_SRC_PATH:-}"
+OVS_SRC_PATH="${OVS_SRC_PATH:-}"
 
 OVNCTL_PATH=/usr/share/ovn/scripts/ovn-ctl
 
@@ -791,7 +792,7 @@ function build-images() {
     os-image-pull
     ${RUNC_CMD} build -t ovn/cinc --build-arg OS_IMAGE=${OS_IMAGE} -f fedora/cinc/Dockerfile .
 
-    ${RUNC_CMD} build -t ovn/ovn-multi-node \
+    ${RUNC_CMD} build -t ovn/ovn-multi-node --build-arg OVS_SRC_PATH=ovs \
     --build-arg OVN_SRC_PATH=ovn --build-arg USE_OVN_RPMS=${USE_OVN_RPMS} \
     --build-arg EXTRA_OPTIMIZE=${EXTRA_OPTIMIZE} \
     --build-arg INSTALL_UTILS_FROM_SOURCES=${INSTALL_UTILS_FROM_SOURCES} \
@@ -812,6 +813,18 @@ function build-images-with-ovn-rpms() {
 }
 
 function build-images-with-ovn-sources() {
+    if [ ! -d ./ovs ]; then
+           echo "OVS_SRC_PATH = $OVS_SRC_PATH"
+           if [ "${OVS_SRC_PATH}" = "" ]; then
+            echo "Set the OVS_SRC_PATH var pointing to the location of ovs source code."
+            exit 1
+           fi
+
+           rm -rf ./ovs
+           cp -rf $OVS_SRC_PATH ./ovs
+           DO_RM_OVS='yes'
+    fi
+
     if [ ! -d ./ovn ]; then
            echo "OVN_SRC_PATH = $OVN_SRC_PATH"
            if [ "${OVN_SRC_PATH}" = "" ]; then
@@ -826,6 +839,7 @@ function build-images-with-ovn-sources() {
     touch tst.rpm
     build-images
     rm -f tst.rpm
+    [ -n "$DO_RM_OVS" ] && rm -rf ovs ||:
     [ -n "$DO_RM_OVN" ] && rm -rf ovn ||:
 }
 
diff --git a/provisioning/grab_ovn_src.sh b/provisioning/grab_ovn_src.sh
index 8777412..b3e9b9d 100755
--- a/provisioning/grab_ovn_src.sh
+++ b/provisioning/grab_ovn_src.sh
@@ -13,8 +13,11 @@ function grab_src {
     fi
 }
 
+OVS_GIT_REPO=${OVS_GIT_REPO:-https://github.com/openvswitch/ovs}
+OVS_BRANCH=${OVS_BRANCH:-master}
 OVN_GIT_REPO=${GIT_REPO:-https://github.com/ovn-org/ovn}
 OVN_BRANCH=${OVN_BRANCH:-main}
 
 cd /vagrant
+grab_src ovs $OVS_BRANCH $OVS_GIT_REPO
 grab_src ovn $OVN_BRANCH $OVN_GIT_REPO

~~~

**Comment by flavio-fernandes** [comment]
> Otherwise OVS binaries (and ovsdb-server) will be built from the sources in the submodule version which is not ideal. We need to be able to test, for example, upstream OVN main against a newer upstream OVS master which includes ovsdb-server improvements but may break some compile-time APIs for libraries used by OVN.

Good point, @dceara . Let me revisit this.

**Review by dceara — APPROVED** [review]

**Pull request merged**
