### PR TITLE
Make podman default

### PR DESCRIPTION
**Pull request by dceara**

### CODE REVIEW

**Comment by flavio-fernandes** [comment]
/lgtm   

TY @dceara !

**Review by flavio-fernandes — APPROVED** [review]
@numansiddique PTAL
Brought up vagrant vm and did some basic podman commands.
One caveat -- not a big deal -- is that podman commands should be done by user root, not user vagrant. I think that is very much ok, agree?

**Comment by numansiddique** [comment]
@flavio-fernandes  I think that is fine.  I guess you are the vagrant user  and probably better person to comment if that's ok :)

**Comment by dceara** [comment]
Thanks @flavio-fernandes and @numansiddique!

**Comment by drizzt** [comment]
this commit breaks vagrant up, at least for me

**Comment by flavio-fernandes** [comment]
> this commit breaks vagrant up, at least for me

sorry to hear tat. Can you give me more details on where it broke fro you?
I was able to vagrant up before merging it. I am using vagrant in a libvirt system.

**Pull request merged**
